### ISSUE TITLE
Support multiple FritzBoxes

### ISSUE THREAD

**Issue by YoSiJo** [jhubig/FritzBoxShell#10]
Please make it possible to use multi FritzBoxes.
For example about the possibility to pass arguments to the script.
```
./fritzBoxShell.sh --host "${IP_OR_DNS?}" --user "${USERNAME?}" --password "${PASSWORD?}"
```

**Comment by volschin** [comment]
You should read https://github.com/jhubig/FritzBoxShell#configuration-script

**Comment by YoSiJo** [comment]
I see, the `BoxIP` exists. Sorry, but i have only show in the docu, not in the scripts.
