### ISSUE TITLE
Use FritzBoxShell With "Login With Password" instead of user and pass in FritzBox 7590 ?

### ISSUE THREAD

**Issue by gtrooper** [jhubig/FritzBoxShell#14]
Hello,

I have to use Login with password in my FritzBox 7590 for an other service to work. Is there any way I could use this amazing tool without logging in to my router via username and pass ? Can I "Login With Password" in FritzBoxShell ?

**Comment by voruti** [comment]
I just tried this as well. Simply leave the username empty and enter the password ...

**Comment by gtrooper** [comment]
Hi there and thanks for taking the time to answer ! I had already tried to leave username blank before I post here but it did not work. I am running FritzOS 6.88 because on FritzOS 7 I had some problems with some scripts that would not run properly, so… for the time being I am forced to stay on 6.88 and there I can't seem to authenticate properly. Could you please tell me what would be the complete command to REBOOT the fritzbox via FritzBoxShell ? I want to do a re-check but I think the authentication problems might go away If I update on FritzOS 7. Are you on FritzOS 7.20 ?

**Comment by voruti** [comment]
I'm indeed on Fritz!OS 7.21:
```
$ ./fritzBoxShellTest.sh
[...]
NewModelName FRITZ!Box 7490
NewSoftwareVersion 113.07.21
```

**Comment by gtrooper** [comment]
I just tried the ./fritzBoxShellTest.sh and indeed I cannot authenticate properly. Although the command WLAN_5G 0 disables the 5G Band and 1 enables it again. So it is only some of the functions that fail to work (like Reboot) probably due to authentication issues..
Thanks for confirming that you are on FritzOS 7 ! I will post again what happens when I update to FritzOS 7 ! Thanks a lot for your help !

**Comment by jhubig** [comment]
Unfortunately I could never test it with releases prio to FritzOS 7. Did you update? Still problems? If not I propose to close the issue. Thanks.

Cheers,
Johannes

**Comment by gtrooper** [comment]
It never worked on 6.88 sadly ! But on a different Fritzbox With FritzOS 7 it works beautifully ! I found an old tool that can reboot the fritz and it works on 6.88 also. So, in the meantime I use that. Thanks for everything  jhubig ! Amazing tool !
