### ISSUE TITLE
Disconnect from and reconnect to WAN

### ISSUE THREAD

**Issue by JayBrown** [jhubig/FritzBoxShell#18]
The following command is possible on my Fritz!Box (7490, OS 7.21), has been for years. No login credentials needed. When executed, you'll get a new IP address from your provider, no reboot necessary. (Unless, of course, you have a static IP anyway.)

`curl -s "http://$fritz_ip:$fritz_port/igdupnp/control/WANIPConn1" -H "Content-Type: text/xml; charset="utf-8"" -H "SoapAction:urn:schemas-upnp-org:service:WANIPConnection:1#ForceTermination" -d "<?xml version='1.0' encoding='utf-8'?> <s:Envelope s:encodingStyle='http://schemas.xmlsoap.org/soap/encoding/' xmlns:s='http://schemas.xmlsoap.org/soap/envelope/'> <s:Body> <u:ForceTermination xmlns:u='urn:schemas-upnp-org:service:WANIPConnection:1' /> </s:Body> </s:Envelope>"` 

Is this already part of FritzBoxShell?

**Comment by gtrooper** [comment]
Are you sure that this command works ? It does not run in my FritzBox 7590 Version 7.21 From macOS Terminal. I mean the command does not show any user error but the new IP never comes.

**Comment by JayBrown** [comment]
It works with my 7490 (FritzOS 7.21). Obviously there are two variables involved `$fritz_ip` and `$fritz_part`, usually IP `192.168.178.1` and port `49000`.

**Comment by JayBrown** [comment]
This is the shell script I'm using:

https://gist.github.com/JayBrown/269d118ee69ffff18e6657e939c194ec

**Comment by gtrooper** [comment]
ok, I have not realized that you use an external script to perform such a simple operation as a "Get a new IP From ISP". Thank you for clarifying that to me.  FritzConnection is an amazing tool that not only does this BUT a WHOLE LOT MORE. So... I don't see the point to create scripts that perform certain things when there are already dedicated tools available that are much more complete.  Anyway, the point is that it would be nice IF fritzboxshell supported this RECONNECT feature. I don't think that it does. Also, When I try to use the REBOOT parameter, it does not work. Does it work for you ? Thanks for taking the time to answer !

**Comment by JayBrown** [comment]
The FritzConnection CLI is new to me. Do you mean this one? https://github.com/kbr/fritzconnection

As for the script: nothing is ever a simple operation. If the reconnect fails, which it could for a couple of reasons, you have to notify the user, and you can't do that without a script. (Especially important if you run it in the background. I usually launch the script from the Touch Bar.) So I would just substitute the cURL command for a fritzconnection command. Amounts to basically the same.

**Comment by gtrooper** [comment]
Hi,

yea I mean that one. I liked what you did there. I tried to test your script and replace fritzconnection command part but I could not get it to work. If you ever have the time and will for replacing it I would be really grateful if you could share ! Thank you in advance ! Although after testing the command reconnect with fritzconnection from CLI it never failed for me but u are right that it is much more useful when you get notification that it ACTUALLY WORKED !

**Comment by jhubig** [comment]
Hello,

sorry for my late response. But I also confirm that the command from the first post (https://github.com/jhubig/FritzBoxShell/issues/18#issue-817487529) is still working on my FritzBox 7490 with the current version 07.29. I have implemented it in FritzBoxShell: https://github.com/jhubig/FritzBoxShell/commit/d677b54f4ffdd4379da182663adba11592ecf210

Therefore I propose to close this issue. Feel free to re-open or add a new one. Thanks.

Cheers,
Johannes
