### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by killerbees19** [jhubig/FritzBoxShell#21]
First of all: Thanks for this great script! 👍

### Maximum password length
Seems like there's a limit of 32 character or byte. (Tested at FRITZ!Box 7530 with FRITZ!OS 07.27)

There's no error while using the webinterface with extra-long passwords, but all TR-064 requests will fail:

```html
<HTML><HEAD><TITLE>401 Unauthorized (ERR_NONE)</TITLE></HEAD><BODY><H1>401 Unauthorized</H1><BR>ERR_NONE<HR><B>Webserver</B> Sat, 07 Aug 2021 11:14:01 GMT</BODY></HTML>
```

Maybe this fact should be mentioned somewhere? (README or Wiki) 😁

### WebPW removed
The removed variable `WebPW` doesn't exist anymore. It should be removed from the example [here](https://github.com/jhubig/FritzBoxShell/wiki/Installation,-Configuration-&-First-test).

**Comment by jhubig** [comment]
Hello,

thanks for your info. Updated the Wiki: https://github.com/jhubig/FritzBoxShell/wiki/Installation,-Configuration-&-First-test/_compare/da37b0f4024310024595cd406b8e4fdce69cd5b9...847483d87a0484ad8b844b37d32d750daf4a2b03

Closed it. If not fitting, please re-open. Thx.

Cheers,
Johannes
