### ISSUE TITLE
Allow changing Wi-Fi signal strength

### ISSUE THREAD

**Issue by Nuklon** [jhubig/FritzBoxShell#29]
Nice script, but it'd be nice if it was possible to change the signal strength to it. When I'm not in my home there's no need for the signal strength to be at 100% 👍

**Comment by jhubig** [comment]
Hello @Nuklon. Sorry for my late reply.
I added the ability in the latest commit (https://github.com/jhubig/FritzBoxShell/commit/17e7c7f1498e2e4c0e600d926b216e01a35a6a0f). Maybe you can retry with the latest version of the fritzBoxShell.sh.

Was working on my FritzBox 7490 with OS 07.29. I will close for the moment but feel free to re-open if it doesn't work for you. Thanks.

Cheers,
Johannes

**Comment by Nuklon** [comment]
Thanks, that's great, I will give it a try when I have some time :)
