### ISSUE TITLE
Feature Request: Possible to switch site-to-site-vpn on and off?

### ISSUE THREAD

**Issue by GatoPharaoh** [jhubig/FritzBoxShell#34]
Hello,

I am currently using my fritzbox to connect to multiple networks over wireguard. as I don't need to have the vpn running 24/7, I wondered if it is possible to enable/disable site-to-site-vpns via script?

thank you very much for the fantastic tool!

![WGDLvAq](https://github.com/jhubig/FritzBoxShell/assets/12106737/5ea43aa1-9577-4ee8-ba73-90f20ef90b9f)

**Comment by b2un0** [comment]
Crazy, had the same question and found this jerere 😅

**Comment by jhubig** [comment]
Sorry for my late response. Functionality added in latest commit: https://github.com/jhubig/FritzBoxShell/commit/5faf4bbadef246c67245bf7afeceb9e889a16175
