### ISSUE TITLE
Info for 7590 7.57: WAN STATE exposes wrong TotalBytes in case of Wireguard VPN is actively used

### ISSUE THREAD

**Issue by pbiering** [jhubig/FritzBoxShell#38]
_just for your information (potentially this can be mentioned on a new "known issue" page in the Wiki_

Scenario: 3 boxes meshed with Wireguard VPN (2x 7490, 1x 7590) and running storage sync jobs accross.

Issue: using MRTG to display rates on the WAN interface the rates displayed for 7590 were approx. factor 2 to high, by retrieving following:
```
SoapAction:urn:dslforum-org:service:WANCommonInterfaceConfig:1#GetTotalBytesReceived
SoapAction:urn:dslforum-org:service:WANCommonInterfaceConfig:1#GetTotalBytesSent
```
Version on 7590: 7.57

Filed ticket to AVM R&D, received a response...known issue, will be fixed in one of the next releases.

Looks like the currrent exposed value is WAN+Wireguard, because value is correct if no traffic is running via Wireguard VPN.

One can watch this also on shell (example, 3rd value is MBit/s) while running transfers (change from "Received" to "Sent" in case of an upload):

```
d=10; val1=0; while true; do val=$(fritzBoxShell.sh  --boxip <IP> --boxuser <USER> --boxpw <PASS> WAN STATE | grep NewTotalBytesReceived | awk '{ print $2 }'); echo $val $val1 $[ ( $val - $val1 ) / $d * 8 / 1000000 ]; val1=$val;sleep $d; done
...
2846852242 2744514536 81
2907927484 2846852242 48
2962761844 2907927484 43
2962863055 2962761844 0
2962889304 2962863055 0
...
```

**Comment by jhubig** [comment]
Agreed. Good idea.
Added a page there: https://github.com/jhubig/FritzBoxShell/wiki/Known-issues

If your ticket is closed or if you have any other future issues, feel free to add them yourself. Due to the fact that reporsitory is public, I guess you can create entries yourself. Thanks for contributing!
