### ISSUE TITLE
Feature request: getting and resetting log

### ISSUE THREAD

**Issue by uahim** [jhubig/FritzBoxShell#41]
which is pretty much the only thing that this script lacks

something like
`curl -k -s -G "http://$BoxIP/query.lua" -d "mq_log=logger:status/log" -d "sid=$SID" | jq -r ".mq_log|.[]|._node?//.[0]" | tac`
to read and
`curl -s "http://$BoxIP/data.lua" --compressed --data "xhr=1&sid=$SID&lang=de&page=log&xhrId=del&del=1&useajax=1&no_sidrenew="`
to reset the log works fine for me, but I guess you could come up with other/more efficient ways!

**Comment by jhubig** [comment]
Hi @uahim,

Sorry for my really late reply. The Christmas holidays are always perfect to go through open issues. Throughout the year it is usually difficult for me. Thanks for the suggestion! You're absolutely right that being able to read and reset the logs is a useful feature.

Currently, this functionality is only achievable through the LUA interface, specifically using the AHA-HTTP-Interface (like you proposed in your comment). I've added the capability to the script (full commit: https://github.com/jhubig/FritzBoxShell/commit/3ee8b6d7d17561d8b3160447cd64f61a8a2c2895), and you can now try it using the following commands:

`fritzBoxShell.sh MISC_LUA ReadLog`
`fritzBoxShell.sh MISC_LUA ResetLog`

This should work as you expect. Let me know how it goes, and feel free to reach out if you need any further assistance or improvements.

Here you can find the latest version of the code: https://github.com/jhubig/FritzBoxShell/archive/refs/heads/master.zip

I will close the issue but feel free to re-open if it does not work for you. Thanks.

Merry Christmas and a happy new year.

Cheers,
Johannes
