### ISSUE TITLE
Triband repeater has two 5G channels 

### ISSUE THREAD

**Issue by michbeck100** [jhubig/FritzBoxShell#43]
For repeaters like Fritz! Repeater 3000 AX (https://avm.de/produkte/wlan-mesh/fritzrepeater-3000-ax/) there is an additional 5G channel which also requires changes to FritzBoxShell. 

The additional channel can be found at 
```
location="/upnp/control/wlanconfig3"
uri="urn:dslforum-org:service:WLANConfiguration:3"
```

Maybe it's possible to add this to the script?

**Comment by jhubig** [comment]
Hello @michbeck100,

You can find the new function in the latest commit (https://github.com/jhubig/FritzBoxShell/commit/5508fa96aa547097b36fe722a199127c149e2392).

Download the latest version here: https://github.com/jhubig/FritzBoxShell/archive/refs/heads/master.zip

Usage

`fritzBoxShell.sh WLAN_5G_CH2 STATE`
`fritzBoxShell.sh WLAN_5G_CH2 STATISTICS`
...

I hope this helps. I will close the issue but feel free to re-open if needed. Thanks.
Cheers,
Johannes
