### ISSUE TITLE
wrong version

### ISSUE THREAD

**Issue by thecijal** [jhubig/FritzBoxShell#44]
Hey there ✌🏼 thx for the cool project!

I downloaded the latest release v1.0.9 by
```bash
wget https://github.com/jhubig/FritzBoxShell/archive/refs/tags/v1.0.9.zip
```
but when I run `./fritzBoxShell.sh VERSION` the output is
**fritzBoxShell.sh version 1.0.8**
... 🤔 

The link to the zip file is from the release page: https://github.com/jhubig/FritzBoxShell/releases/tag/v1.0.9

I'm wondering what's causing this behaviour because [this commit](https://github.com/jhubig/FritzBoxShell/commit/a84f1d3cf9134d0e1c5f1994b63f1cf273b302e2) actually looks like the fix 😅 

Regarding [this issue](https://github.com/jhubig/FritzBoxShell/issues/27): Do the zip / tar.gz artifacts currently need to be build manually?

**Comment by thecijal** [comment]
Indeed the `fritzBoxShell.sh` script of the v1.0.9 release contains the old version number 🙂 

![image](https://github.com/jhubig/FritzBoxShell/assets/41804849/aa684018-9a30-44cc-8d2c-40a16de3e14b)

FYI: The date of the [v1.0.9 release](https://github.com/jhubig/FritzBoxShell/releases/tag/v1.0.9) is `Apr 16, 2023` and the [commit](https://github.com/jhubig/FritzBoxShell/commit/a84f1d3cf9134d0e1c5f1994b63f1cf273b302e2) that corrects the version was created on `Dec 28, 2023`. So I assume the released zip/tar.gz artifacts just do not contain the fix yet.

Sorry for noticing this after creating the issue.

**Comment by jhubig** [comment]
Sorry. But I forgot again to update the version string before the release. Updated now: https://github.com/jhubig/FritzBoxShell/releases/tag/v1.0.9

Thanks for the hint.

**Comment by thecijal** [comment]
Hi there again 👋🏼 How about an automated release creation [like this one](https://github.com/jhubig/FritzBoxShell/pull/46)? 🙂
