### ISSUE TITLE
block / unblock internet access via KIDS

### ISSUE THREAD

**Issue by eazyliving** [jhubig/FritzBoxShell#49]
Hiho everybody :)

I'd love to use this function and it somehow works. But...

To block a machine, you need the deviceID, something like "landevice6062".
To unblock the machine, you need a userID, something like "user1581", deviceID won't work!

The problem now is, that the deviceID seems to be persistent, but the userID increases on every block. I checked that via the webinterface and inspected the request data. 

Now I'll write some wrap to store and increase the userID on every block, that should work for now in case no other action increases userIDs...

Can anybody verify that or am I holding it wrong? I'd love to be corrected :-)

**Comment by eazyliving** [comment]
well... found another way to fit my needs.

It's possible to put a device into a profile group. So I can move my sons computer into a profile without restrictions for giving him net and put it into a restricted group for the way back.

That would look like that:

`
wget -O /dev/null  --post-data "sid=$SID&dev_name=$option2&dev=$option3&kisi_profile=$option4&page=edit_device&apply=true" "http://$BoxIP/data.lua" 2>/dev/null
`

where option2 would be the devices name, option3 the devices ID an option4 the profiles name.

Why name and ID for the device? Not sure, but you need to provide a name while omitting the deviceID. That could result in selecting the wrong device, since names are not unique ("iPhone"...).

You can get the names and IDs via inspection the requests. Device name should be obvious. The ID is smth like landeviceXYZ, the profile is smth like filterprofXYZ.

Hope, that helps. Should I put that into a pull request?

**Comment by jhubig** [comment]
Hello,

great that you found a solution. To be honest, I did not play with that functionality yet. My kids are still to young to have their own devices. But the day will come 😃.

So...yes. Feel free to put it into a pull request. I also might need that. Thank you!

Cheers,
Johannes

**Comment by eazyliving** [comment]
I made a PR for SETPROFILE :)
