### ISSUE TITLE
Controll WOL a tool with which you can turn devices on and off via the WOl  function from the Fritzbox

### ISSUE THREAD

**Issue by AMXX1679** [jhubig/FritzBoxShell#51]
a tool with which you can turn devices on and off via the Fritzbox

**Comment by jhubig** [comment]
Yes, it is possible to turn on devices via Wake-on-LAN (WOL) using a shell script and the TR-064 interface of the FritzBox. However, it is not possible to turn off devices directly through the FritzBox, as WOL only supports turning on devices by sending a so-called "Magic Packet." For turning them off you have to use different methods like for example a shutdown command via ssh on linux machines.

I have implemented the WakeOnLAN function in the latest script (commit😀https://github.com/jhubig/FritzBoxShell/commit/1cae13496e7c22283e52b71d83d58ca5125c2e6a): https://github.com/jhubig/FritzBoxShell/archive/refs/heads/master.zip

**Usage**
`fritzBoxShell.sh WOL "<YourMAC>"`

I will close the issue, but feel free to re-open if necessary. Thanks.

Cheers,
Johannes
